use super::*;
use crate::{
    jwk::Jwk, PrivateKeyToJwk, PublicKeyToJwk, SigningKey, VerificationKey, URL_SAFE_TRAILING_BITS,
};
use base64::Engine as _;
use rsa_crt::{
    pkcs1v15, pss,
    traits::{PrivateKeyParts, PublicKeyParts},
    BigUint, RsaPrivateKey as CratePrivateKey, RsaPublicKey as CratePublicKey,
};
use sha2::{Sha256, Sha384, Sha512};
use signature::{SignatureEncoding, Signer, Verifier};
use smallvec::SmallVec;

/// RSA Private Key.
///
/// By default, it only verifies signatures generated by the same algorithm
/// used for signing. If you want to verify signatures generated by any RSA
/// algorithm, set `verify_any` to `true`.
#[derive(Debug, Clone)]
pub struct RsaPrivateKey {
    pub(crate) private_key: CratePrivateKey,
    pub algorithm: RsaAlgorithm,
    pub verify_any: bool,
}

impl RsaPrivateKey {
    pub fn generate(bits: usize, algorithm: RsaAlgorithm) -> Result<Self> {
        if bits < 2048 {
            return Err(Error::UnsupportedOrInvalidKey);
        }

        let private_key = CratePrivateKey::new(&mut rand_core::OsRng, bits)
            .map_err(|e| Error::Crypto(Box::new(e)))?;
        Ok(Self {
            private_key,
            algorithm,
            verify_any: false,
        })
    }

    pub fn from_components(
        n: &[u8],
        e: &[u8],
        d: &[u8],
        primes: Vec<Vec<u8>>,
        algorithm: RsaAlgorithm,
    ) -> Result<Self> {
        let n = BigUint::from_bytes_be(n);
        let e = BigUint::from_bytes_be(e);
        let d = BigUint::from_bytes_be(d);
        let primes: Vec<BigUint> = primes
            .into_iter()
            .map(|p| BigUint::from_bytes_be(&p))
            .collect();
        let private_key = CratePrivateKey::from_components(n, e, d, primes)
            .map_err(|e| Error::Crypto(Box::new(e)))?;
        if private_key.n().bits() < 2048 {
            return Err(Error::UnsupportedOrInvalidKey);
        }
        Ok(Self {
            private_key,
            algorithm,
            verify_any: false,
        })
    }

    pub fn n(&self) -> Vec<u8> {
        self.private_key.n().to_bytes_be()
    }

    pub fn e(&self) -> Vec<u8> {
        self.private_key.e().to_bytes_be()
    }
}

impl PrivateKeyToJwk for RsaPrivateKey {
    fn private_key_to_jwk(&self) -> Result<Jwk> {
        let n = self.n();
        let e = self.e();
        let d = self.private_key.d().to_bytes_be();
        let primes = self.private_key.primes();

        fn encode(x: &[u8]) -> String {
            URL_SAFE_TRAILING_BITS.encode(x)
        }

        let (p, q, dp, dq, qi) = if primes.len() >= 2 {
            let p = &primes[0];
            let q = &primes[1];
            let one = BigUint::from(1u32);
            let dp = self.private_key.d() % (p - &one);
            let dq = self.private_key.d() % (q - &one);
            // qi = q^(p-2) mod p (Fermat's little theorem)
            let qi = q.modpow(&(p - BigUint::from(2u32)), p);
            (
                Some(encode(&p.to_bytes_be())),
                Some(encode(&q.to_bytes_be())),
                Some(encode(&dp.to_bytes_be())),
                Some(encode(&dq.to_bytes_be())),
                Some(encode(&qi.to_bytes_be())),
            )
        } else {
            (None, None, None, None, None)
        };

        Ok(Jwk {
            kty: "RSA".into(),
            alg: if self.verify_any {
                None
            } else {
                Some(self.algorithm.name().into())
            },
            use_: Some("sig".into()),
            n: Some(encode(&n)),
            e: Some(encode(&e)),
            d: Some(encode(&d)),
            p,
            q,
            dp,
            dq,
            qi,
            ..Default::default()
        })
    }
}

impl PublicKeyToJwk for RsaPrivateKey {
    fn public_key_to_jwk(&self) -> Result<Jwk> {
        Ok(Jwk {
            kty: "RSA".into(),
            alg: if self.verify_any {
                None
            } else {
                Some(self.algorithm.name().into())
            },
            use_: Some("sig".into()),
            n: Some(URL_SAFE_TRAILING_BITS.encode(self.n())),
            e: Some(URL_SAFE_TRAILING_BITS.encode(self.e())),
            ..Jwk::default()
        })
    }
}

/// RSA Public Key.
#[derive(Debug, Clone)]
pub struct RsaPublicKey {
    pub(crate) public_key: CratePublicKey,
    /// If this is `None`, this key verifies signatures generated by ANY RSA
    /// algorithms. Otherwise it ONLY verifies signatures generated by this
    /// algorithm.
    pub algorithm: Option<RsaAlgorithm>,
}

impl RsaPublicKey {
    pub fn from_components(n: &[u8], e: &[u8], algorithm: Option<RsaAlgorithm>) -> Result<Self> {
        let n = BigUint::from_bytes_be(n);
        let e = BigUint::from_bytes_be(e);
        let public_key = CratePublicKey::new(n, e).map_err(|e| Error::Crypto(Box::new(e)))?;
        if public_key.n().bits() < 2048 {
            return Err(Error::UnsupportedOrInvalidKey);
        }
        Ok(Self {
            public_key,
            algorithm,
        })
    }

    pub fn n(&self) -> Vec<u8> {
        self.public_key.n().to_bytes_be()
    }

    pub fn e(&self) -> Vec<u8> {
        self.public_key.e().to_bytes_be()
    }
}

impl PublicKeyToJwk for RsaPublicKey {
    fn public_key_to_jwk(&self) -> Result<Jwk> {
        Ok(Jwk {
            kty: "RSA".into(),
            alg: self.algorithm.map(|alg| alg.name().to_string()),
            use_: Some("sig".into()),
            n: Some(URL_SAFE_TRAILING_BITS.encode(self.n())),
            e: Some(URL_SAFE_TRAILING_BITS.encode(self.e())),
            ..Jwk::default()
        })
    }
}

macro_rules! rsa_sign {
    (pkcs1v15, $hash:ty, $key:expr, $msg:expr) => {{
        let sk = pkcs1v15::SigningKey::<$hash>::new($key.clone());
        let sig: pkcs1v15::Signature = sk.try_sign($msg).map_err(|e| Error::Crypto(Box::new(e)))?;
        Ok(sig.to_bytes().to_vec().into())
    }};
    (pss, $hash:ty, $key:expr, $msg:expr) => {{
        let sk = pss::SigningKey::<$hash>::new($key.clone());
        let sig: pss::Signature = sk.try_sign($msg).map_err(|e| Error::Crypto(Box::new(e)))?;
        Ok(sig.to_bytes().to_vec().into())
    }};
}

impl SigningKey for RsaPrivateKey {
    fn sign(&self, v: &[u8]) -> Result<SmallVec<[u8; 64]>> {
        use RsaAlgorithm::*;
        match self.algorithm {
            RS256 => rsa_sign!(pkcs1v15, Sha256, self.private_key, v),
            RS384 => rsa_sign!(pkcs1v15, Sha384, self.private_key, v),
            RS512 => rsa_sign!(pkcs1v15, Sha512, self.private_key, v),
            PS256 => rsa_sign!(pss, Sha256, self.private_key, v),
            PS384 => rsa_sign!(pss, Sha384, self.private_key, v),
            PS512 => rsa_sign!(pss, Sha512, self.private_key, v),
        }
    }

    fn alg(&self) -> &'static str {
        self.algorithm.name()
    }
}

macro_rules! rsa_verify_pkcs1v15 {
    ($hash:ty, $key:expr, $msg:expr, $sig:expr) => {{
        let vk = pkcs1v15::VerifyingKey::<$hash>::new($key.clone());
        let sig = pkcs1v15::Signature::try_from($sig).map_err(|_| Error::VerificationError)?;
        vk.verify($msg, &sig).map_err(|_| Error::VerificationError)
    }};
}

macro_rules! rsa_verify_pss {
    ($hash:ty, $key:expr, $msg:expr, $sig:expr) => {{
        let vk = pss::VerifyingKey::<$hash>::new($key.clone());
        let sig = pss::Signature::try_from($sig).map_err(|_| Error::VerificationError)?;
        vk.verify($msg, &sig).map_err(|_| Error::VerificationError)
    }};
}

fn rsa_verify(alg: RsaAlgorithm, public_key: &CratePublicKey, v: &[u8], sig: &[u8]) -> Result<()> {
    use RsaAlgorithm::*;
    match alg {
        RS256 => rsa_verify_pkcs1v15!(Sha256, public_key, v, sig),
        RS384 => rsa_verify_pkcs1v15!(Sha384, public_key, v, sig),
        RS512 => rsa_verify_pkcs1v15!(Sha512, public_key, v, sig),
        PS256 => rsa_verify_pss!(Sha256, public_key, v, sig),
        PS384 => rsa_verify_pss!(Sha384, public_key, v, sig),
        PS512 => rsa_verify_pss!(Sha512, public_key, v, sig),
    }
}

impl VerificationKey for RsaPrivateKey {
    fn verify(&self, v: &[u8], sig: &[u8], alg: &str) -> Result<()> {
        let alg = if self.verify_any {
            RsaAlgorithm::from_name(alg)?
        } else {
            if alg != self.algorithm.name() {
                return Err(Error::VerificationError);
            }
            self.algorithm
        };
        rsa_verify(alg, self.private_key.as_ref(), v, sig)
    }
}

impl VerificationKey for RsaPublicKey {
    fn verify(&self, v: &[u8], sig: &[u8], alg: &str) -> Result<()> {
        let alg = if let Some(self_alg) = self.algorithm {
            if self_alg.name() != alg {
                return Err(Error::VerificationError);
            }
            self_alg
        } else {
            RsaAlgorithm::from_name(alg)?
        };
        rsa_verify(alg, &self.public_key, v, sig)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sign_verify() -> Result<()> {
        for alg in [
            RsaAlgorithm::RS256,
            RsaAlgorithm::RS384,
            RsaAlgorithm::RS512,
            RsaAlgorithm::PS256,
            RsaAlgorithm::PS384,
            RsaAlgorithm::PS512,
        ] {
            let k = RsaPrivateKey::generate(2048, alg)?;
            let pk = RsaPublicKey::from_components(&k.n(), &k.e(), None)?;
            let sig = k.sign(b"...")?;
            assert!(k.verify(b"...", &sig, alg.name()).is_ok());
            assert!(k.verify(b"...", &sig, "WRONG ALG").is_err());
            assert!(k.verify(b"....", &sig, alg.name()).is_err());
            assert!(pk.verify(b"...", &sig, alg.name()).is_ok());
            assert!(pk.verify(b"....", &sig, alg.name()).is_err());
        }
        Ok(())
    }

    #[test]
    fn jwk_roundtrip() -> Result<()> {
        let k = RsaPrivateKey::generate(2048, RsaAlgorithm::PS256)?;
        let jwk = k.private_key_to_jwk()?;
        let k1 = jwk.to_signing_key(RsaAlgorithm::RS256)?;
        let sig = k1.sign(b"msg")?;
        k.verify(b"msg", &sig, "PS256")?;
        k1.verify(b"msg", &sig, "PS256")?;
        let sig = k.sign(b"msg")?;
        k1.verify(b"msg", &sig, "PS256")?;
        Ok(())
    }

    #[test]
    fn jwk_n_e_d_only() -> Result<()> {
        let k = RsaPrivateKey::generate(2048, RsaAlgorithm::PS256)?;
        let mut jwk = k.private_key_to_jwk()?;
        jwk.p = None;
        jwk.q = None;
        jwk.dp = None;
        jwk.dq = None;
        jwk.qi = None;
        let k1 = jwk.to_signing_key(RsaAlgorithm::RS256)?;
        let sig = k1.sign(b"msg")?;
        k.verify(b"msg", &sig, "PS256")?;
        k1.verify(b"msg", &sig, "PS256")?;
        let sig = k.sign(b"msg")?;
        k1.verify(b"msg", &sig, "PS256")?;
        Ok(())
    }

    #[test]
    fn public_key_jwk() -> Result<()> {
        let k = RsaPrivateKey::generate(2048, RsaAlgorithm::RS256)?;
        let jwk = k.public_key_to_jwk()?;
        let pk = jwk.to_verification_key()?;
        let sig = k.sign(b"hello")?;
        pk.verify(b"hello", &sig, "RS256")?;
        Ok(())
    }
}
